# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'begin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 580)
        Form.setMinimumSize(QtCore.QSize(800, 580))
        Form.setMaximumSize(QtCore.QSize(800, 580))
        Form.setSizeIncrement(QtCore.QSize(800, 580))
        Form.setStyleSheet("background-color: #E6E9ED")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 0, 791, 581))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 791, 561))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_34 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_34.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.gridLayout.addWidget(self.line_34, 10, 3, 1, 1)
        self.line_25 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.gridLayout.addWidget(self.line_25, 4, 7, 1, 1)
        self.line_26 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.gridLayout.addWidget(self.line_26, 8, 7, 1, 1)
        self.line_27 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.gridLayout.addWidget(self.line_27, 2, 7, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label6 = QtWidgets.QLabel(self.frame_16)
        self.label6.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label6.setFont(font)
        self.label6.setText("")
        self.label6.setAlignment(QtCore.Qt.AlignCenter)
        self.label6.setObjectName("label6")
        self.ckbox6 = QtWidgets.QCheckBox(self.frame_16)
        self.ckbox6.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox6.setObjectName("ckbox6")
        self.gridLayout.addWidget(self.frame_16, 4, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 7, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 9, 0, 1, 1)
        self.line_39 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_39.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.gridLayout.addWidget(self.line_39, 1, 8, 1, 1)
        self.line_35 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_35.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.gridLayout.addWidget(self.line_35, 10, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.frame_23 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.label12 = QtWidgets.QLabel(self.frame_23)
        self.label12.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label12.setFont(font)
        self.label12.setText("")
        self.label12.setAlignment(QtCore.Qt.AlignCenter)
        self.label12.setObjectName("label12")
        self.ckbox12 = QtWidgets.QCheckBox(self.frame_23)
        self.ckbox12.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox12.setObjectName("ckbox12")
        self.gridLayout.addWidget(self.frame_23, 6, 2, 1, 1)
        self.frame_21 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.label7 = QtWidgets.QLabel(self.frame_21)
        self.label7.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label7.setFont(font)
        self.label7.setText("")
        self.label7.setAlignment(QtCore.Qt.AlignCenter)
        self.label7.setObjectName("label7")
        self.ckbox7 = QtWidgets.QCheckBox(self.frame_21)
        self.ckbox7.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox7.setObjectName("ckbox7")
        self.gridLayout.addWidget(self.frame_21, 4, 2, 1, 1)
        self.frame_28 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.label4 = QtWidgets.QLabel(self.frame_28)
        self.label4.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label4.setFont(font)
        self.label4.setText("")
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        self.ckbox4 = QtWidgets.QCheckBox(self.frame_28)
        self.ckbox4.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox4.setObjectName("ckbox4")
        self.gridLayout.addWidget(self.frame_28, 2, 6, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbeasy = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rbeasy.setObjectName("rbeasy")
        self.horizontalLayout.addWidget(self.rbeasy)
        self.rbdiff = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rbdiff.setObjectName("rbdiff")
        self.horizontalLayout.addWidget(self.rbdiff)
        self.rball = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rball.setObjectName("rball")
        self.horizontalLayout.addWidget(self.rball)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_18 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.verticalLayout_2.addWidget(self.line_18)
        self.select_all = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.select_all.setMinimumSize(QtCore.QSize(0, 0))
        self.select_all.setObjectName("select_all")
        self.verticalLayout_2.addWidget(self.select_all)
        self.mselect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mselect.setObjectName("mselect")
        self.verticalLayout_2.addWidget(self.mselect)
        self.gridLayout.addLayout(self.verticalLayout_2, 10, 4, 1, 1)
        self.frame_22 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.label2 = QtWidgets.QLabel(self.frame_22)
        self.label2.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label2.setFont(font)
        self.label2.setText("")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.ckbox2 = QtWidgets.QCheckBox(self.frame_22)
        self.ckbox2.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox2.setObjectName("ckbox2")
        self.gridLayout.addWidget(self.frame_22, 2, 2, 1, 1)
        self.frame_24 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.label8 = QtWidgets.QLabel(self.frame_24)
        self.label8.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label8.setFont(font)
        self.label8.setText("")
        self.label8.setAlignment(QtCore.Qt.AlignCenter)
        self.label8.setObjectName("label8")
        self.ckbox8 = QtWidgets.QCheckBox(self.frame_24)
        self.ckbox8.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox8.setObjectName("ckbox8")
        self.gridLayout.addWidget(self.frame_24, 4, 4, 1, 1)
        self.frame_31 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.label3 = QtWidgets.QLabel(self.frame_31)
        self.label3.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label3.setFont(font)
        self.label3.setText("")
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName("label3")
        self.ckbox3 = QtWidgets.QCheckBox(self.frame_31)
        self.ckbox3.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox3.setObjectName("ckbox3")
        self.gridLayout.addWidget(self.frame_31, 2, 4, 1, 1)
        self.line_36 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_36.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.gridLayout.addWidget(self.line_36, 0, 3, 1, 1)
        self.line_42 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_42.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.gridLayout.addWidget(self.line_42, 8, 3, 1, 1)
        self.line_45 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_45.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.gridLayout.addWidget(self.line_45, 9, 2, 1, 1)
        self.line_41 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_41.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.gridLayout.addWidget(self.line_41, 0, 5, 1, 1)
        self.line_43 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_43.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.gridLayout.addWidget(self.line_43, 8, 5, 1, 1)
        self.line_46 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_46.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.gridLayout.addWidget(self.line_46, 9, 6, 1, 1)
        self.line_44 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_44.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.gridLayout.addWidget(self.line_44, 9, 4, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.label13 = QtWidgets.QLabel(self.frame_26)
        self.label13.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label13.setFont(font)
        self.label13.setText("")
        self.label13.setAlignment(QtCore.Qt.AlignCenter)
        self.label13.setObjectName("label13")
        self.ckbox13 = QtWidgets.QCheckBox(self.frame_26)
        self.ckbox13.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox13.setObjectName("ckbox13")
        self.gridLayout.addWidget(self.frame_26, 6, 4, 1, 1)
        self.frame_17 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label11 = QtWidgets.QLabel(self.frame_17)
        self.label11.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label11.setFont(font)
        self.label11.setText("")
        self.label11.setAlignment(QtCore.Qt.AlignCenter)
        self.label11.setObjectName("label11")
        self.ckbox11 = QtWidgets.QCheckBox(self.frame_17)
        self.ckbox11.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox11.setObjectName("ckbox11")
        self.gridLayout.addWidget(self.frame_17, 6, 0, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout.addWidget(self.line_20, 2, 1, 1, 1)
        self.line_33 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.gridLayout.addWidget(self.line_33, 2, 3, 1, 1)
        self.line_29 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.gridLayout.addWidget(self.line_29, 4, 5, 1, 1)
        self.line_30 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.gridLayout.addWidget(self.line_30, 6, 5, 1, 1)
        self.line_22 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout.addWidget(self.line_22, 6, 1, 1, 1)
        self.line_32 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.gridLayout.addWidget(self.line_32, 4, 3, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout.addWidget(self.line_21, 4, 1, 1, 1)
        self.line_24 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.gridLayout.addWidget(self.line_24, 6, 7, 1, 1)
        self.line_23 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout.addWidget(self.line_23, 8, 1, 1, 1)
        self.line_28 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.gridLayout.addWidget(self.line_28, 2, 5, 1, 1)
        self.line_31 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.gridLayout.addWidget(self.line_31, 6, 3, 1, 1)
        self.frame_29 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.label9 = QtWidgets.QLabel(self.frame_29)
        self.label9.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label9.setFont(font)
        self.label9.setText("")
        self.label9.setAlignment(QtCore.Qt.AlignCenter)
        self.label9.setObjectName("label9")
        self.ckbox9 = QtWidgets.QCheckBox(self.frame_29)
        self.ckbox9.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox9.setObjectName("ckbox9")
        self.gridLayout.addWidget(self.frame_29, 4, 6, 1, 1)
        self.frame_30 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.label14 = QtWidgets.QLabel(self.frame_30)
        self.label14.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label14.setFont(font)
        self.label14.setText("")
        self.label14.setAlignment(QtCore.Qt.AlignCenter)
        self.label14.setObjectName("label14")
        self.ckbox14 = QtWidgets.QCheckBox(self.frame_30)
        self.ckbox14.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox14.setObjectName("ckbox14")
        self.gridLayout.addWidget(self.frame_30, 6, 6, 1, 1)
        self.line_40 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_40.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.gridLayout.addWidget(self.line_40, 1, 2, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout.addWidget(self.line_17, 9, 8, 1, 1)
        self.line_49 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_49.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.gridLayout.addWidget(self.line_49, 10, 7, 1, 1)
        self.line_48 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_48.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.gridLayout.addWidget(self.line_48, 10, 1, 1, 1)
        self.line_50 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_50.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.gridLayout.addWidget(self.line_50, 0, 7, 1, 1)
        self.line_47 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_47.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.gridLayout.addWidget(self.line_47, 0, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 7, 2, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 3, 4, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 5, 4, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 3, 8, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 3, 6, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 3, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 5, 2, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout.addWidget(self.line_16, 7, 4, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 5, 8, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 5, 6, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout.addWidget(self.line_14, 7, 8, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout.addWidget(self.line_15, 7, 6, 1, 1)
        self.frame_18 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label1 = QtWidgets.QLabel(self.frame_18)
        self.label1.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label1.setFont(font)
        self.label1.setText("")
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.ckbox1 = QtWidgets.QCheckBox(self.frame_18)
        self.ckbox1.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox1.setObjectName("ckbox1")
        self.gridLayout.addWidget(self.frame_18, 2, 0, 1, 1)
        self.frame_27 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.label5 = QtWidgets.QLabel(self.frame_27)
        self.label5.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label5.setFont(font)
        self.label5.setText("")
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5.setObjectName("label5")
        self.ckbox5 = QtWidgets.QCheckBox(self.frame_27)
        self.ckbox5.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox5.setObjectName("ckbox5")
        self.gridLayout.addWidget(self.frame_27, 2, 8, 1, 1)
        self.frame_32 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.label15 = QtWidgets.QLabel(self.frame_32)
        self.label15.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label15.setFont(font)
        self.label15.setText("")
        self.label15.setAlignment(QtCore.Qt.AlignCenter)
        self.label15.setObjectName("label15")
        self.ckbox15 = QtWidgets.QCheckBox(self.frame_32)
        self.ckbox15.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox15.setObjectName("ckbox15")
        self.gridLayout.addWidget(self.frame_32, 6, 8, 1, 1)
        self.frame_33 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.label10 = QtWidgets.QLabel(self.frame_33)
        self.label10.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label10.setFont(font)
        self.label10.setText("")
        self.label10.setAlignment(QtCore.Qt.AlignCenter)
        self.label10.setObjectName("label10")
        self.ckbox10 = QtWidgets.QCheckBox(self.frame_33)
        self.ckbox10.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox10.setObjectName("ckbox10")
        self.gridLayout.addWidget(self.frame_33, 4, 8, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout.addWidget(self.line_19, 1, 4, 1, 1)
        self.line_38 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.gridLayout.addWidget(self.line_38, 1, 6, 1, 1)
        self.line_37 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.gridLayout.addWidget(self.line_37, 1, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.label16 = QtWidgets.QLabel(self.frame_19)
        self.label16.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label16.setFont(font)
        self.label16.setText("")
        self.label16.setAlignment(QtCore.Qt.AlignCenter)
        self.label16.setObjectName("label16")
        self.ckbox16 = QtWidgets.QCheckBox(self.frame_19)
        self.ckbox16.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox16.setObjectName("ckbox16")
        self.gridLayout.addWidget(self.frame_19, 8, 2, 1, 1)
        self.frame_25 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.label17 = QtWidgets.QLabel(self.frame_25)
        self.label17.setGeometry(QtCore.QRect(0, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label17.setFont(font)
        self.label17.setText("")
        self.label17.setAlignment(QtCore.Qt.AlignCenter)
        self.label17.setObjectName("label17")
        self.ckbox17 = QtWidgets.QCheckBox(self.frame_25)
        self.ckbox17.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.ckbox17.setObjectName("ckbox17")
        self.gridLayout.addWidget(self.frame_25, 8, 6, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ckbox6.setText(_translate("Form", "就你了"))
        self.label.setText(_translate("Form", "选题类型"))
        self.ckbox12.setText(_translate("Form", "就你了"))
        self.ckbox7.setText(_translate("Form", "就你了"))
        self.ckbox4.setText(_translate("Form", "就你了"))
        self.rbeasy.setText(_translate("Form", "简\n"
"单"))
        self.rbdiff.setText(_translate("Form", "困\n"
"难"))
        self.rball.setText(_translate("Form", "都\n"
"要"))
        self.select_all.setText(_translate("Form", "全选进入"))
        self.mselect.setText(_translate("Form", "选择好了"))
        self.ckbox2.setText(_translate("Form", "就你了"))
        self.ckbox8.setText(_translate("Form", "就你了"))
        self.ckbox3.setText(_translate("Form", "就你了"))
        self.ckbox13.setText(_translate("Form", "就你了"))
        self.ckbox11.setText(_translate("Form", "就你了"))
        self.ckbox9.setText(_translate("Form", "就你了"))
        self.ckbox14.setText(_translate("Form", "就你了"))
        self.ckbox1.setText(_translate("Form", "就你了"))
        self.ckbox5.setText(_translate("Form", "就你了"))
        self.ckbox15.setText(_translate("Form", "就你了"))
        self.ckbox10.setText(_translate("Form", "就你了"))
        self.ckbox16.setText(_translate("Form", "就你了"))
        self.ckbox17.setText(_translate("Form", "就你了"))

